### ISSUE TITLE
命令の説明が表示されていません

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3doc#13]
書くのはここでいいんでしょうか。
各命令の、説明とか引数とか、wikiから編集出来る「詳しい解説」の上の部分が表示されなくなっちゃってます。
https://nadesi.com/v3/doc/index.php?plugin_system%2F%E5%BC%95&show

また、「plugin_system」などの、一覧表示もされなくなっています。
https://nadesi.com/v3/doc/index.php?plugin_system&show

もしかしたら、サーバーのGit設定がうまくいかないの件に関連して、既知のことなのかもですが、いちおうご報告でした。

**Comment by kujirahand** [comment]
先日のWIKIバージョンアップで設定がリセットされていました。
修正しました！
ご報告に感謝です。

**Comment by snowdrops89** [comment]
ありがとうございます☆
