### ISSUE TITLE
カナ順の命令一覧になぜか漢字があります

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3doc#15]
全然たいしたことではないのですが・・・
どういうわけか、平方根が「平」、論理＊＊が「論」になっているんです。
また、論理ORが表示されていないようです（●だけになってる？）
この一覧ページは、自動生成されているんですよね？
タブン、元の命令のデータの振り仮名部分に間違いがあるんだと思うのですが・・・

**Comment by kujirahand** [comment]
以下で処理します。
https://github.com/kujirahand/nadesiko3/issues/828

**Comment by kujirahand** [comment]
修正しました！

**Comment by snowdrops89** [comment]
素早い対応で、ありがとうございます！
nadesiko3の命令の//@の後ろの振り仮名が入っていないと、元の命令の漢字になってしまっていたって事だったんですね。
たぶん、空では無くて、間違った物が入っているものもあるようです。
文字描画が（がぞうびょうが）になっていたり、ODBC実行がSに入っていたり、GETデータとPOSTデータがWに入っていたりしています。あと、TOFLOATとTOINTは英語なのに、TOSTRだけは（とぅーすとりんぐ）で「と」に入ってるってどうなんだ？とかｗ
今さらでスミマセン。おぉ～もう直ってる～♪　と、眺めていて気がついたもので……
どこを直したら良いか分かったので本当はわたしが直せたら良いんですけど……GitHubがいまだによく分からずorz

**Comment by kujirahand** [comment]
ご報告ありがとうございます！
改めて修正しました。
もし、見つけたら気軽に教えてください！
なでしこのソースコードに直接ふりがなが書かれていますので。

**Comment by snowdrops89** [comment]
ありがとうございます！！
