### ISSUE TITLE
目次が欲しい

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3doc#16]
ｖ３の命令一覧は、ずっとスクロールしないと目的の項目に辿り着けないのが不便で、ｖ１の命令一覧のような、目次が欲しい所です。（#15 は、それで作ってみようとしていて気が付きました）
現在の「v3.1.18に対応」とゆう形でなら私にもすぐ作成出来そうなのですが、マニュアルに目次のページを追加してみてもよいでしょうか？
しかし、今後も命令が増えたり、プラグインが増えたりということを考えると、命令一覧と同時に目次も自動生成される方が良いのでは無いかと思ったりして。

**Comment by kujirahand** [comment]
@snowdrops89 ありがとうございます。

目次なんですが、PHPで自動で生成しているんです。
data/nako3commands.db
のSQLiteのDBを基に生成しています。

konawiki3のプラグインが以下です。
https://github.com/kujirahand/konawiki3/blob/master/kona3engine/plugins/nako3doc.inc.php

なお、script/cmd2db.nako3
これで、上記nako3commands.dbを生成しているのです。

それでも、全部なでしこ３で自動生成できると良いかもですね。
バージョンアップごとに、スクリプト実行すれば良いだけなので。
何か良い方法がありますか？

(メモ) 現在借りているWebサーバーでは、Node.jsが動かせないので仕方なくPHPで自動生成しています。

**Comment by kujirahand** [comment]
@snowdrops89 さん、ありがとうございます。
下記のプログラム、マニュアルページに埋め込んでも良いですか？？？

https://nadesi.com/v3/storage/id.php?453
https://nadesi.com/v3/storage/id.php?451

**Comment by snowdrops89** [comment]
あっ、ありがとうございます！！
試しにちょっと作ってみただけなのですが、こんなので良かったでしょうか？
ちなみにデータの部分は、ｖ１で命令一覧のページをHTTPデータ取得して作っただけなので、プラグインが追加になったりした場合は作り直さねばならぬのですｗｗｗ

**Comment by snowdrops89** [comment]
ちょっと修正をして、スマホとかでもいい感じに（？）見れるようにしてみました☆
このデータの部分だけでも、phpででも、命令一覧を生成するときに、ついでに生成できたらよきな感じなんですけれどね（素人考え）
項目へのリンク先がいるので、command.txtからじゃダメなんですよねー。

**Comment by kujirahand** [comment]
@snowdrops89 さん、ありがとうございます。
とりあえず、nako3storageの書き込みをそのままブログ部品として貼り付けてみました。

なんか、各種コマンド情報が得られるAPIを作ると、JSON形式でページリンクとか取り出せて楽しいかもですね。
考えてみます。

**Comment by snowdrops89** [comment]
ありがとうございます！！
とってもべんりになりました♪♪♪
