### ISSUE TITLE
ディレクトリ構造や構築手順をKonawiki3に対応させる

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3doc#3]
Konawiki3では以下のようにGitリポジトリを置いて差分管理を行いますが、それに合ったディレクトリ構造・構築手順になっていないので改善します。

```
konawiki3/
- data/ <- ここにGitリポジトリを置いてWikiデータの差分を管理する
```

**Comment by kujirahand** [comment]
もともと、konawiki3は、index.phpとkonawiki3.ini.phpの二つのファイルがあれば、konawiki3を何も変えずに作業できるようになっています。konawiki3.ini.phpに、konawiki3/kona3engineのパスを指定すれば動かすことができます。各プロジェクトの独立性を保つ上でも、現状の動作で良い気がするのですがどうでしょうか？

https://github.com/kujirahand/nadesiko3doc/blob/master/README.md

**Comment by massongit** [comment]
なるほどです。
READMEに記載された通りの方法で環境構築して確認してみましたが、うまく動作したので問題なさそうですね。
